### ISSUE TITLE
Create album from multiple image uploads

### ISSUE THREAD

**Issue by ghost** [arthow4n/minimgur#1]
Am I blind or is this feature missing? It seems like an essential feature.

Cheers for the app, I love the straightforward/barebones simplicity of it, especially because it's without neglecting the design.

**Comment by ghost** [comment]
I think there's a way to create a single link from multiple image IDs which makes it generate a page with all the images on it like a gallery.

I don't know if the API requires you to upload images as a gallery from the start in order to make one.

**Comment by arthow4n** [comment]
Hi there, yes it's missing, and according to [Imgur Album Creation API](https://api.imgur.com/endpoints/album#album-upload), this seems doable.

But I don't think it is essential to this app. This app was made for posting direct links of uploaded images on a forum which supports showing these images within the same page. So external imgur album link is not the use case.

**Comment by ghost** [comment]
Thought I'd let you know my mate and I stopped using the app because it lacks this feature.

¯\\_\_(ツ)_\_/¯
